### ISSUE TITLE
Backend overhaul

### ISSUE THREAD

**Issue by umulmrum** [chameleon-system/chameleon-system#96]
**Describe the solution you'd like**
The backend needs some love. This is a parent ticket in which we collect ideas on improving usability and beauty. This ticket should focus on measures that are noticeable by users - technical improvements should only be done with that in mind, not for code cleanup/refactoring purposes.

Constraints:
- Please try to reduce inline JavaScript. We really need to be able to add strict CSP rules in the long run.
- As these changes are done in minor versions, it is desirable to make every change opt-out-able so that users can adapt to the changes at their own pace. If we introduce changes too fast, users might be confused and disapprove the new features. Of course there are limits for what we can technically achieve, so do not strive to preserve opt-out-ability at any cost.

-----

- [x] Bootstrap 4 Upgrade: #185 
- [x] Backend theme: #99 
- [x] Sidebar menu: #100
- [ ] ~~Breadcrumb instead of history: #101~~
- [ ] ~~Improve list usability: #102~~
- [ ] ~~Dashboard: #103~~
- [ ] ~~Improve multi-language editing: #104~~
- [ ] ~~Improve navigation tree #107~~
- [x] Main menu item order: #155 
- [ ] ~~Perspectives: #156~~
- [ ] ~~Show content in new window: #157~~
- [x] Replace icons with font and remove unused #178
- [x] Replace jQuery UI components with BS4 components #204 
- [x] Replace old color picker with bootstrap 4 compatible version #245 
- [x] Replace search field in lists with autocomplete select2 box #256
